In [3]:
import numpy as np
a=np.random.random((3,4))
print(a)

[[0.60474594 0.04008253 0.82421551 0.57481767]
 [0.34641667 0.94710278 0.00355908 0.86341675]
 [0.0073836  0.15551633 0.21370836 0.68046408]]


In [10]:
import numpy as np
a=np.arange(5,30,2)
print(a)

[ 5  7  9 11 13 15 17 19 21 23 25 27 29]


In [18]:
import numpy as np 
a=np.zeros([3,4])
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
print("Dimensions",a.ndim)
print("Shape",a.shape)
print("Datatype",a.dtype)

Dimensions 2
Shape (3, 4)
Datatype float64


In [22]:
b=a.flatten()
print("The flatten Array:\n",b)

The flatten Array:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
