In [2]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
r=np.hstack((a,b))
print(r)

[[1 2 5 6]
 [3 4 7 8]]


In [3]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
r=np.vstack((a,b))
print(r)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [5]:
 import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
r=np.dstack((a,b))
print(r)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [6]:
import numpy as np
a=np.array([1,2,3,4,5,6])
r=np.split(a,3)
print(r)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [9]:
import numpy as np
a=np.array([1,2,3,4,5])
r=np.array_split(a,3)
print(r)

[array([1, 2]), array([3, 4]), array([5])]
