In [2]:
import numpy as np
a=np.array([1,3,5,8,6,9,2])
x=np.where(a==6)
print(x)

(array([4]),)


In [3]:
import numpy as np
a=np.array([1,3,5,8,6,9,2])
x=np.where(a==8)
print(x)

(array([3]),)


In [8]:
import numpy as np
a=np.array([1,6,2,7,6,4])
x=np.where(a%2==0)
print(x)

(array([1, 2, 4, 5]),)


In [9]:
import numpy as np
a=np.array([1,6,2,7,6,4])
x=np.where(a%3==1)
print(x)

(array([0, 3, 5]),)


In [12]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
x=np.searchsorted(a,8,side='left')
print(x)

7


In [13]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
x=np.searchsorted(a,8,side='right')
print(x)

8


In [15]:
import numpy as np 
a= np.array([9,5,2,7,6,4])
print(np.sort(a))

[2 4 5 6 7 9]


In [16]:
import numpy as np 
a= np.array([[7,4,9],[9,1,4]])
print(np.sort(a))

[[4 7 9]
 [1 4 9]]


In [17]:
import numpy as np 
a=np.array([31,78,69,100])
x=[False,True,False,True]
na=a[x]
print(x)
print(na)

                                                                            

[False, True, False, True]
[ 78 100]


In [21]:
import numpy as np
a=np.array([31,78,69,100])
filter_a=a>70
nw=a[filter_a]
print(nw)


[ 78 100]
