In [3]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
slice1=a[0:4]
print(slice1)

[1 2 3 4]


In [6]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
slice2=a[::2]
print(slice2)

[1 3 5 7 9]


In [7]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
reverse=a[::-1]
print(reverse)

[9 8 7 6 5 4 3 2 1]


In [8]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
s=a[0:2,1:3]
print(s)

[[2 3]
 [5 6]]


In [9]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
s=a[:2,:1]
print(s)

[[1]
 [4]]


In [11]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
c=a[:,0]
print(c)

[1 4 7]


In [14]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
r=a[0,:]
print(r)


[1 2 3]


In [15]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
rr=a[0:2:1]
print(rr)

[[1 2 3]
 [4 5 6]]
